package banco.views;

import banco.controllers.ClienteBean;
import banco.domains.Cliente;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.SQLSyntaxErrorException;

/**
 *
 * @author polar
 */
public class JFCliente extends javax.swing.JFrame {

    /**
     * Creates new form JFCliente
     */
    public JFCliente() {
        initComponents();
        listarClientes();
        desativarBotoes();
        jBtnInserir.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGSexo = new javax.swing.ButtonGroup();
        jBtnGCivil = new javax.swing.ButtonGroup();
        jPnlCliente = new javax.swing.JPanel();
        jLblCodigo = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLblSexo = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        jLblTelefone = new javax.swing.JLabel();
        jTxtCivil = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jTxtTelefone = new javax.swing.JTextField();
        jBtnInserir = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jRBtnM = new javax.swing.JRadioButton();
        jRBtnF = new javax.swing.JRadioButton();
        jRBtnSolteiro = new javax.swing.JRadioButton();
        jRBtnCasado = new javax.swing.JRadioButton();
        jRBtnDivorciado = new javax.swing.JRadioButton();
        jRBtnViuvo = new javax.swing.JRadioButton();
        jPnlClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblCodigo.setText("Código");

        jLblNome.setText("Nome");

        jLblSexo.setText("Sexo");

        jLblEmail.setText("Email");

        jLblTelefone.setText("Tel.");

        jTxtCivil.setText("Civil");

        jTxtCodigo.setEnabled(false);
        jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoActionPerformed(evt);
            }
        });

        jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailActionPerformed(evt);
            }
        });

        jBtnInserir.setText("Inserir");
        jBtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInserirActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Limpar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnGSexo.add(jRBtnM);
        jRBtnM.setText("M");
        jRBtnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnMActionPerformed(evt);
            }
        });

        jBtnGSexo.add(jRBtnF);
        jRBtnF.setText("F");

        jBtnGCivil.add(jRBtnSolteiro);
        jRBtnSolteiro.setText("Solteiro(a)");
        jRBtnSolteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnSolteiroActionPerformed(evt);
            }
        });

        jBtnGCivil.add(jRBtnCasado);
        jRBtnCasado.setText("Casado(a)");

        jBtnGCivil.add(jRBtnDivorciado);
        jRBtnDivorciado.setText("Divorciado(a)");

        jBtnGCivil.add(jRBtnViuvo);
        jRBtnViuvo.setText("Viúvo(a)");

        javax.swing.GroupLayout jPnlClienteLayout = new javax.swing.GroupLayout(jPnlCliente);
        jPnlCliente.setLayout(jPnlClienteLayout);
        jPnlClienteLayout.setHorizontalGroup(
            jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlClienteLayout.createSequentialGroup()
                        .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblSexo)
                            .addComponent(jLblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlClienteLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jRBtnM)
                                .addGap(18, 18, 18)
                                .addComponent(jRBtnF)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPnlClienteLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTxtNome))))
                    .addGroup(jPnlClienteLayout.createSequentialGroup()
                        .addComponent(jLblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEmail))
                    .addGroup(jPnlClienteLayout.createSequentialGroup()
                        .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlClienteLayout.createSequentialGroup()
                                .addComponent(jLblTelefone)
                                .addGap(4, 4, 4))
                            .addComponent(jTxtCivil, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlClienteLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jTxtTelefone))
                            .addGroup(jPnlClienteLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRBtnCasado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBtnSolteiro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBtnDivorciado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBtnViuvo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPnlClienteLayout.createSequentialGroup()
                        .addComponent(jBtnInserir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnCancelar)
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(jPnlClienteLayout.createSequentialGroup()
                        .addComponent(jLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jTxtCodigo)))
                .addContainerGap())
        );
        jPnlClienteLayout.setVerticalGroup(
            jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNome)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSexo)
                    .addComponent(jRBtnM)
                    .addComponent(jRBtnF))
                .addGap(18, 18, 18)
                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEmail)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelefone)
                    .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBtnSolteiro)
                            .addComponent(jRBtnDivorciado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBtnCasado)
                            .addComponent(jRBtnViuvo)))
                    .addGroup(jPnlClienteLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jTxtCivil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnInserir)
                    .addComponent(jBtnEditar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        jPnlClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTblClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Sexo", "Email", "Telefone", "Civil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblClientes.setShowGrid(true);
        jTblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblClientes);
        if (jTblClientes.getColumnModel().getColumnCount() > 0) {
            jTblClientes.getColumnModel().getColumn(0).setMinWidth(40);
            jTblClientes.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTblClientes.getColumnModel().getColumn(0).setMaxWidth(120);
            jTblClientes.getColumnModel().getColumn(1).setMinWidth(200);
            jTblClientes.getColumnModel().getColumn(1).setPreferredWidth(400);
            jTblClientes.getColumnModel().getColumn(1).setMaxWidth(600);
            jTblClientes.getColumnModel().getColumn(2).setMinWidth(40);
            jTblClientes.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTblClientes.getColumnModel().getColumn(2).setMaxWidth(120);
            jTblClientes.getColumnModel().getColumn(3).setMinWidth(200);
            jTblClientes.getColumnModel().getColumn(3).setPreferredWidth(400);
            jTblClientes.getColumnModel().getColumn(3).setMaxWidth(600);
            jTblClientes.getColumnModel().getColumn(4).setMinWidth(100);
            jTblClientes.getColumnModel().getColumn(4).setPreferredWidth(200);
            jTblClientes.getColumnModel().getColumn(4).setMaxWidth(400);
            jTblClientes.getColumnModel().getColumn(5).setMinWidth(75);
            jTblClientes.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTblClientes.getColumnModel().getColumn(5).setMaxWidth(300);
        }

        javax.swing.GroupLayout jPnlClientesLayout = new javax.swing.GroupLayout(jPnlClientes);
        jPnlClientes.setLayout(jPnlClientesLayout);
        jPnlClientesLayout.setHorizontalGroup(
            jPnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlClientesLayout.setVerticalGroup(
            jPnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        if (jTxtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o nome", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (jBtnGSexo.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Selecione o sexo", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (jTxtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o email", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (jTxtTelefone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o telefone", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (jBtnGCivil.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Selecione o estado civil", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            char sexo = 0;
            String civil = null; 
            if (jRBtnF.isSelected()) {
                sexo = 'F';
            }
            if (jRBtnM.isSelected()) {
                sexo = 'M';
            }
            if (jRBtnSolteiro.isSelected()) {
                civil = "Solteiro(a)";
            }
            if (jRBtnCasado.isSelected()) {
                civil = "Casado(a)";
            }
            if (jRBtnDivorciado.isSelected()) {
                civil = "Divorciado(a)";
            }
            if (jRBtnViuvo.isSelected()) {
                civil = "Viúvo(a)";
            }
            Cliente cliente = new Cliente(jTxtNome.getText(), sexo, jTxtEmail.getText(), jTxtTelefone.getText(), civil);
            cliente.setId(Integer.parseInt(jTxtCodigo.getText()));
            ClienteBean clienteBean = new ClienteBean();

            clienteBean.editarCliente(cliente);
            JOptionPane.showMessageDialog(null, "Registro editado com sucesso", "Informação", JOptionPane.WARNING_MESSAGE);

            limpar();
            listarClientes();
            desativarBotoes();
            jBtnInserir.setEnabled(true);
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jRBtnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBtnMActionPerformed

    private void jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        limpar();
        desativarBotoes();
        jBtnInserir.setEnabled(true);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInserirActionPerformed
        // TODO add your handling code here:
        if (jTxtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o nome", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (jBtnGSexo.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Selecione o sexo", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (jTxtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o email", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (jTxtTelefone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o telefone", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else if (jBtnGCivil.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Selecione o estado civil", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            char sexo = 0;
            String civil = null; 
            if (jRBtnF.isSelected()) {
                sexo = 'F';
            }
            if (jRBtnM.isSelected()) {
                sexo = 'M';
            }
            if (jRBtnSolteiro.isSelected()) {
                civil = "Solteiro(a)";
            }
            if (jRBtnCasado.isSelected()) {
                civil = "Casado(a)";
            }
            if (jRBtnDivorciado.isSelected()) {
                civil = "Divorciado(a)";
            }
            if (jRBtnViuvo.isSelected()) {
                civil = "Viúvo(a)";
            }
            Cliente cliente = new Cliente(jTxtNome.getText(), sexo, jTxtEmail.getText(), jTxtTelefone.getText(), civil);
            ClienteBean clienteBean = new ClienteBean();

            
            try {
                clienteBean.inserirCliente(cliente);
                JOptionPane.showMessageDialog(null, "Registro inserido com sucesso", "Informação", JOptionPane.WARNING_MESSAGE);
            } catch (SQLSyntaxErrorException ex) {
                JOptionPane.showMessageDialog(null, "ERRO 001\nReporte este erro ao desenvolvedor", "Erro", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            } catch (SQLIntegrityConstraintViolationException ex) {
                JOptionPane.showMessageDialog(null, "Nome já registrado no banco de dados", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Outro problema com o banco de dados", "Erro", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            
            limpar();
            listarClientes();
        }
    }//GEN-LAST:event_jBtnInserirActionPerformed

    private void jTblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblClientesMouseClicked
        // TODO add your handling code here:
        jTxtCodigo.setText(String.valueOf(jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 0)));
        jTxtNome.setText(String.valueOf(jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 1)));
        jTxtEmail.setText(String.valueOf(jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 3)));
        jTxtTelefone.setText(String.valueOf(jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 4)));

        if (jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 2).equals('M')) {
            jRBtnM.setSelected(true);
        }

        if (jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 2).equals('F')) {
            jRBtnF.setSelected(true);
        }
        
        if (jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 5).equals("Solteiro(a)")) {
            jRBtnSolteiro.setSelected(true);
        }

        if (jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 5).equals("Casado(a)")) {
            jRBtnCasado.setSelected(true);
        }
        
        if (jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 5).equals("Divorciado(a)")) {
            jRBtnDivorciado.setSelected(true);
        }

        if (jTblClientes.getValueAt(jTblClientes.getSelectedRow(), 5).equals("Viúvo(a)")) {
            jRBtnViuvo.setSelected(true);
        }
        
        ativarBotoes();
        jBtnInserir.setEnabled(false);
    }//GEN-LAST:event_jTblClientesMouseClicked

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (jTxtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            char sexo = 0;
            String civil = null; 
            if (jRBtnF.isSelected()) {
                sexo = 'F';
            }
            if (jRBtnM.isSelected()) {
                sexo = 'M';
            }
            if (jRBtnSolteiro.isSelected()) {
                civil = "Solteiro(a)";
            }
            if (jRBtnCasado.isSelected()) {
                civil = "Casado(a)";
            }
            if (jRBtnDivorciado.isSelected()) {
                civil = "Divorciado(a)";
            }
            if (jRBtnViuvo.isSelected()) {
                civil = "Viúvo(a)";
            }
            Cliente cliente = new Cliente(jTxtNome.getText(), sexo, jTxtEmail.getText(), jTxtTelefone.getText(), civil);
            cliente.setId(Integer.parseInt(jTxtCodigo.getText()));
            ClienteBean clienteBean = new ClienteBean();

            int confirmacao = JOptionPane.showConfirmDialog(null, "Confirma a exclusão permanente do registro?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirmacao == JOptionPane.YES_OPTION) {
                clienteBean.excluirCliente(cliente);
                JOptionPane.showMessageDialog(null, "Registro excluído com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
                limpar();
                listarClientes();
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada pelo usuário", "Informação", JOptionPane.INFORMATION_MESSAGE);
                limpar();
            }

            limpar();
            listarClientes();
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailActionPerformed

    private void jRBtnSolteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnSolteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBtnSolteiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.ButtonGroup jBtnGCivil;
    private javax.swing.ButtonGroup jBtnGSexo;
    private javax.swing.JButton jBtnInserir;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblSexo;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JPanel jPnlCliente;
    private javax.swing.JPanel jPnlClientes;
    private javax.swing.JRadioButton jRBtnCasado;
    private javax.swing.JRadioButton jRBtnDivorciado;
    private javax.swing.JRadioButton jRBtnF;
    private javax.swing.JRadioButton jRBtnM;
    private javax.swing.JRadioButton jRBtnSolteiro;
    private javax.swing.JRadioButton jRBtnViuvo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblClientes;
    private javax.swing.JLabel jTxtCivil;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtTelefone;
    // End of variables declaration//GEN-END:variables

    public void ativarBotoes() {
        jBtnInserir.setEnabled(true);
        jBtnEditar.setEnabled(true);
        jBtnExcluir.setEnabled(true);
        jBtnCancelar.setEnabled(true);
    }
    
    public void desativarBotoes() {
        jBtnInserir.setEnabled(false);
        jBtnEditar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jBtnCancelar.setEnabled(false);
    }
    
    public void limpar() {
        jTxtCodigo.setText("");
        jTxtNome.setText("");
        jTxtEmail.setText("");
        jTxtTelefone.setText("");
        jTxtNome.setText("");
        jBtnGSexo.clearSelection();
        jBtnGCivil.clearSelection();
        jTblClientes.clearSelection();
    }

    public void listarClientes() {
        List<Cliente> clientes = new ArrayList<>();
        ClienteBean clienteController = new ClienteBean();

        clientes = clienteController.listarClientes();

        DefaultTableModel modeloTabela = (DefaultTableModel) jTblClientes.getModel();
        modeloTabela.setRowCount(0);

        for (Cliente cliente : clientes) {
            Object[] linha = new Object[]{cliente.getId(), cliente.getNome(), cliente.getSexo(), cliente.getEmail(), cliente.getTelefone(), cliente.getCivil()};
            modeloTabela.addRow(linha);
        }
    }
}
